spring:
  application:
    name: projetoPI
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grupo4
    username: infra
    password: "infra"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 630177904220-m0htlila7b9easlrkvdaeo2f1ehs9u3e.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/calendar
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            issuer-uri: https://accounts.google.com
  main:
    allow-circular-references: true

google:
  calendar:
    application-name: "beauty-agenda"
    salon:
      calendar-id: "primary"
      credentials-file: "classpath:salao.json"
server:
  error:
    include-message: always
    include-binding-error: always

jwt:
  validity: 3600000
  secret: RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YXRhbWVudGUgcGFyYSBxdWUgZGUgdG9kbyBvIFVuaXZlcnNvIGUgcG9yIHF1ZSBlbGUgZXN04SBhcnJpc2NhdmVsLCBlbGUgZGVzYXBhcmljZSBpbnN0YW5lYSBzdWJzdGl0dWNvbiBwZXJmaXRvLi4u

aws:
  regiao: us-east-1
  s3:
    nome-bucket: beauty-barreto-source

springdoc:
  swagger-ui:
    path: /swagger-ui.html   # Caminho da interface do Swagger UI
  api-docs:
    path: /v3/api-docs       # Caminho do JSON da documentação

web-endpoint:
  url: "http://localhost:5173"